version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tweb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3310"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker/entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  app:
    image: python:3.10
    container_name: python_app
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tweb
    ports:
      - "5000:5000"
    restart: always

volumes:
  db_data: